Repository Charcoal-SE/SmokeDetector, pull requests merged in 2018-03, with the labels that each got.

#1699 Circle config
  .circleci/config.yml
  circle.yml
  tox.ini
Labels: tests

#1677 Show reasons that would have been caught for !!/report posts
  chatcommands.py
  test/test_chatcommands.py
Labels: commands

#1624 Deletionwatcher refactor
  chatcommands.py
  chatcommunicate.py
  deletionwatcher.py
  spamhandling.py
  tasks.py
  ws.py
Labels: refactor efforts
