Repository Charcoal-SE/SmokeDetector, pull requests merged in 2023-04, with the labels that each got.

#7706 Add pytest-timeout and set 300 second per-test timeout
  .circleci/config.yml
  .github/workflows/build.yml
  requirements.txt
Labels: area: CI testing, type: enhancement

#7714 Update README to indicate we don’t support Python 3.6
  README.md
Labels: area: documentation, type: enhancement

#7727 Blogspot updates 02
  watched_keywords.txt
Labels: type: refactor

#7728 generalized most of the blogspot entries to remove the TLD portion
  watched_keywords.txt
Labels: type: refactor
